---
- name: Install PHP and required packages
  apt:
    name:
      - php
      - zip
      - php-mysql
      - php-gd
      - php-xml
      - php-mbstring
      - libapache2-mod-php
      - php-zip
      - php-mysqli
    state: present

- name: Restart Apache after installing PHP
  service:
    name: apache2
    state: restarted

- name: Enable php7.4 module
  apache2_module:
    name: php7.4
    state: present
