---
- name: Install vsftpd
  yum:
    name: vsftpd
    state: present

- name: Copy vsftpd.conf file
  copy:
    src: files/vsftpd.conf
    dest: /etc/vsftpd.conf
    owner: root
    group: root
    mode: "0644"


- name: Create vsftpd user list file and add powermin user
  lineinfile:
    path: /etc/vsftpd.userlist
    line: "{{ apache_user }}"
    create: yes
    state: present
  notify:
    - restart vsftpd

